name: Sleeper Autologin

on:
  schedule:
    - cron: "15 20 */6 * *"
    - cron: "15 20 1 * *"
  workflow_dispatch:

jobs:
  autologin:
    runs-on: ubuntu-latest
    steps:
      - uses: esfalsa/autologin-action@main
        with:
          user_agent: esfalsa
          credentials: ${{ secrets.SLEEPER_CREDENTIALS }}
